# Generated by Django 3.2.6 on 2023-01-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_auto_20230126_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='start_date',
        ),
        migrations.AddField(
            model_name='goal',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
