# Generated by Django 3.2.6 on 2023-01-27 03:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='date',
        ),
        migrations.CreateModel(
            name='BankBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=16)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_balances', to='accounts.bankaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
